//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2._2_Database_to_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stores
    {
        public string StoreID { get; set; }
        public string StoreLocation { get; set; }
        public string StoreTel { get; set; }
    }
}
